### ISSUE TITLE
There is an error in executing to hexacopter_s.c

### ISSUE THREAD

**Issue by MohamedArbani** [AvalancheMustache/ArtvaSearchAlgorithm#1]
There is an error in executing to hexacopter_s.c. Please, if there is a solution to this problem : 
     The S-function 'hexacopter_s' cannot be found or has not been compiled. For help, see the documentation "Compile S-Functions to be Compatible with Polyspace".
Error using main (line 119)
Error in 'hexacopter/Algoritmo Adattativo/Ricevitore con mean sampler/Modello Ricevitore/Rumore Misura Qt':
Failed to evaluate mask initialization commands.
Caused by:
    Error using main (line 119)
    The covariance matrix must be symmetric and nonnegative definite.

**Comment by MatteoRagni** [comment]
Hi there, I think it is as simple as compiling the s-function hexacopter_s.
